# Generated by Django 4.2.16 on 2024-09-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=15)),
                ('moment', models.DateTimeField(auto_now_add=True)),
                ('message_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_project', to='project.project')),
            ],
        ),
    ]
